import type { NextPage } from 'next';
import Head from 'next/head';
import React from "react";
import useRealtimeCursor from '../src/client/useRealtimeCursor';
import { CursorEye } from '../components/CursorEye';
import styles from '../styles/Home.module.css';
import { CustomCursorViewParameter } from '../src/components/CursorAnimate';



const Home: NextPage = () => {
    const { onMouseMove, renderCursors } = useRealtimeCursor()

    /**カスタムビューを設定したい場合 */
    const customView = (param: CustomCursorViewParameter) => {
        return (<CursorEye userInfo={param.userInfo} />)
    }

    return (
        <div className={styles.container} onMouseMove={onMouseMove}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                {renderCursors()}

            </main>
        </div>
    )
}

export default Home
