import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useEffect, useState } from "react";
import useCreateRealtimeCursor from '../api/gqlFunctions/useCreateRealtimeCursor';
import useOnCreateRealtimeCursor from '../api/gqlFunctions/useOnCreateRealtimeCursor';
import useRealtimeCursor from '../client/useRealtimeCursor';
import { CursorAnimate } from '../components/CursorAnimate';
import User from '../models/User';
import styles from '../styles/Home.module.css';



const Home: NextPage = () => {
    const { pushRealtimeCursor, cursorList } = useRealtimeCursor()

    const [time, setTime] = useState(0)
    const [yourCursorPosition, setYourCursorPosition] = useState({ x: 0, y: 0 })


    const _onMouseMove = (e) => {
        setYourCursorPosition({ x: e.clientX, y: e.clientY });
    }

    useEffect(() => {
        const timer = setTimeout(() => {
            setTime(time + 1);
            if (!yourCursorPosition.x) return
            if (!yourCursorPosition.y) return
            pushRealtimeCursor(yourCursorPosition.x, yourCursorPosition.y)
        }, 500);
        return () => {
            clearTimeout(timer);
        };
    }, [time]);

    const renderCursors = () => {
        return cursorList.map(c => {
            return (
                <CursorAnimate
                    key={c.key}
                    curPos={{ x: c.x, y: c.y }}
                    userInfo={{ name: c.name, avatar: c.avator, color: c.color }} />
            )
        })
    }

    return (
        <div className={styles.container} onMouseMove={_onMouseMove}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>
                <h1 className={styles.title}>
                    Welcome to <a href="https://nextjs.org">Next.js!</a>
                </h1>

                {renderCursors()}


            </main>
        </div>
    )
}

export default Home
