import type { NextPage } from 'next';
import Head from 'next/head';
import React, { useEffect, useState } from "react";
import { CSSTransition } from 'react-transition-group';
import useCreateRealtimeCursor from '../api/gqlFunctions/useCreateRealtimeCursor';
import useCreateUserAction from '../api/gqlFunctions/useCreateUserAction';
import useOnCreateRealtimeCursor from '../api/gqlFunctions/useOnCreateRealtimeCursor';
import useOnCreateUserAction from '../api/gqlFunctions/useOnCreateUserAction';
import NormalButton from '../components/NormalButton';
import User from '../models/User';
import styles from '../styles/Home.module.css';
import style from "./button.module.css";

export async function getServerSideProps(context: any) {
    // URL情報は取れる
    const host = context.req.headers.host
    const path = context.resolvedUrl
    const url = host + path
    return {
        props: {
            url: url
        },
    };

}


const Home: NextPage = (props: any) => {
    const [fire1, setFire1] = useState(false)
    const [fire2, setFire2] = useState(false)
    const [fire3, setFire3] = useState(false)

    const { url } = props
    const [createUserAction] = useCreateUserAction()

    //Subscription
    const onCreateUserAction = useOnCreateUserAction(url)

    const onClick = (actionId: string) => {
        const user = new User()
        const actionIdAndUserId = `ActionId#${actionId}UserId#${user.userId}`
        //TODO: urlに"URL#"つけ忘れて気づかなかった。。。。
        createUserAction({ variables: { url: "URL#" + url, actionIdAndUserId, actionId, value: "clicked", updatedAt: user.updatedAt } })
    }


    useEffect(() => {
        const createdAction = onCreateUserAction.data?.onCreateUserAction
        console.log(createdAction)
        if (!createdAction) {
            console.warn(onCreateUserAction.data)
            return
        }
        const actionId = createdAction.actionId
        if (actionId === "button_1") {
            setFire1(true)
        } else if (actionId === "button_2") {
            setFire2(true)
        } else if (actionId === "button_3") {
            setFire3(true)
        }
    }, [onCreateUserAction.data])



    return (
        <div className={styles.container}>
            <Head>
                <title>Create Next App</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>

            <main className={styles.main}>

                <CSSTransition
                    in={!fire1}
                    timeout={500}
                    onExited={() => setFire1(false)}
                    classNames={{
                        enterActive: style.enterActive,
                        enterDone: style.enterDone,
                        exitActive: style.exitActive,
                        exitDone: style.exitDone
                    }}>
                    <NormalButton onClick={() => onClick("button_1")} />
                </CSSTransition>
                <div style={{ height: 10 }} />
                <CSSTransition
                    in={!fire2}
                    timeout={500}
                    onExited={() => setFire2(false)}
                    classNames={{
                        enterActive: style.enterActive,
                        enterDone: style.enterDone,
                        exitActive: style.exitActive,
                        exitDone: style.exitDone
                    }}>
                    <NormalButton onClick={() => onClick("button_2")} />
                </CSSTransition>
                <div style={{ height: 10 }} />

                <CSSTransition
                    in={!fire3}
                    timeout={500}
                    onExited={() => setFire3(false)}
                    classNames={{
                        enterActive: style.enterActive,
                        enterDone: style.enterDone,
                        exitActive: style.exitActive,
                        exitDone: style.exitDone
                    }}>
                    <NormalButton onClick={() => onClick("button_3")} />
                </CSSTransition>


            </main>
        </div>
    )
}

export default Home